<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Categoria;
use App\Models\Producto;
use Illuminate\Support\Str;

class CategoriaSeeder extends Seeder
{
    public function run(): void
    {
        $categorias = [
            // Correas - uso viene de la antigua descripcion_corta, descripcion_corta viene de la antigua descripcion
            ['producto' => 'Correas', 'nombre' => 'Correas Lisas', 'uso' => 'Transmisión de potencia', 'descripcion_corta' => 'Correas industriales de alta resistencia para transmisión de potencia', 'descripcion' => 'Las correas lisas, o trapezoidales, son bandas de transmisión flexibles que unen dos o más poleas para transferir fuerza y movimiento. Tienen una sección transversal en forma de "V" que encaja en ranuras similares de las poleas. Esto aumenta el agarre, evita que resbalen y mejora la eficiencia.'],
            ['producto' => 'Correas', 'nombre' => 'Correas Dentadas', 'uso' => 'Transmisión precisa', 'descripcion_corta' => 'Correas sincronizadas para transmisión precisa', 'descripcion' => 'Una correa dentada es una cinta flexible con dientes en su cara interior. Estos dientes engranan en poleas especiales como lo hacen los dientes de dos engranajes. Este sistema elimina el deslizamiento y permite una sincronización exacta entre piezas móviles.'],
            ['producto' => 'Correas', 'nombre' => 'Correas Sincronas', 'uso' => 'Velocidad variable', 'descripcion_corta' => 'Correas para sistemas de velocidad variable', 'descripcion' => 'Las correas síncronas (o correas dentadas) son bandas planas con dientes internos que engranan con poleas ranuradas. Transmiten movimiento exacto sin resbalar. Funcionan como una cadena de bicicleta, pero son de caucho y fibra. Proveen alta eficiencia y no requieren lubricación.'],
            ['producto' => 'Correas', 'nombre' => 'Correas Acanaladas', 'uso' => 'Alta eficiencia', 'descripcion_corta' => 'Correas multicanales para alta eficiencia', 'descripcion' => 'Una correa acanalada es una banda flexible con múltiples ranuras en forma de "V" en su interior. Transmite energía desde un motor a otras partes de una máquina. Son muy eficientes porque sus canales aumentan el agarre, lo que evita que resbalen.'],

            // Mangueras
            ['producto' => 'Mangueras', 'nombre' => 'Mangueras Hidráulicas', 'uso' => 'Alta presión', 'descripcion_corta' => 'Mangueras de alta presión para sistemas hidráulicos industriales', 'descripcion' => 'Las mangueras hidráulicas son tubos flexibles diseñados para transportar líquidos a alta presión (como el aceite hidráulico) entre partes de una máquina. Transmiten la fuerza necesaria para mover equipos pesados como excavadoras y tractores. Su flexibilidad ayuda a absorber las vibraciones del motor.'],
            ['producto' => 'Mangueras', 'nombre' => 'Mangueras de Succión y Descarga', 'uso' => 'Transferencia de fluidos', 'descripcion_corta' => 'Mangueras para transferencia de fluidos', 'descripcion' => 'Las mangueras de succión y descarga mueven líquidos y sólidos entre lugares. Son tubos flexibles que conectan bombas de agua. Funcionan aspirando líquidos (vacío) o empujándolos con fuerza (presión).'],
            ['producto' => 'Mangueras', 'nombre' => 'Mangueras Multiusos', 'uso' => 'Versátiles', 'descripcion_corta' => 'Mangueras versátiles para múltiples aplicaciones', 'descripcion' => 'Las mangueras multiusos son tubos flexibles diseñados para transportar varios tipos de fluidos como agua, aire y aceites en una sola herramienta.'],
            ['producto' => 'Mangueras', 'nombre' => 'Mangueras Neumáticas', 'uso' => 'Aire comprimido', 'descripcion_corta' => 'Mangueras para sistemas de aire comprimido', 'descripcion' => 'Las mangueras neumáticas son tubos flexibles que llevan aire a presión desde un compresor hacia máquinas o herramientas. Son clave en fábricas y talleres. Funcionan como las venas del sistema. Mueven la fuerza del aire para hacer girar, levantar o cortar piezas.'],

            // Rodamientos
            ['producto' => 'Rodamientos', 'nombre' => 'Rodamientos de Rodillos', 'uso' => 'Cargas pesadas', 'descripcion_corta' => 'Rodamientos para cargas pesadas', 'descripcion' => 'Los rodamientos de rodillos son piezas mecánicas que reducen la fricción entre ejes giratorios y otras partes de una máquina. Usan cilindros o barriles en lugar de bolas. Este diseño crea una línea de contacto. Como resultado, soportan cargas mucho más pesadas y resisten mejor los golpes que los rodamientos de bolas.'],
            ['producto' => 'Rodamientos', 'nombre' => 'Rodamientos de Bolas', 'uso' => 'Alta velocidad', 'descripcion_corta' => 'Rodamientos de precisión para alta velocidad', 'descripcion' => 'Un rodamiento de bolas es una pieza mecánica que reduce la fricción entre partes móviles. Usa pequeñas esferas de metal que ruedan entre dos anillos. Esto permite que las piezas giren rápido y suavemente. Es como usar ruedas de patines para mover cosas pesadas con poco esfuerzo.'],
            ['producto' => 'Rodamientos', 'nombre' => 'Rodamientos de Agujas', 'uso' => 'Compactos', 'descripcion_corta' => 'Rodamientos compactos para espacios reducidos', 'descripcion' => 'Los rodamientos de agujas son cojinetes que usan rodillos cilíndricos muy finos y largos. Soportan cargas radiales pesadas en espacios muy pequeños. El contacto entre el rodillo y la pista es lineal, lo que distribuye el peso de manera uniforme.'],
            ['producto' => 'Rodamientos', 'nombre' => 'Rodamientos Axiales', 'uso' => 'Cargas axiales', 'descripcion_corta' => 'Rodamientos para cargas axiales', 'descripcion' => 'Los rodamientos axiales, o rodamientos de empuje, soportan fuerzas paralelas al eje de rotación. Funcionan como una prensa que aprieta hacia abajo. Se dividen en tres tipos principales: de bolas para alta velocidad, de rodillos para cargas extremas, y esféricos que corrigen errores de alineación.'],
            ['producto' => 'Rodamientos', 'nombre' => 'Rodamientos Lineales', 'uso' => 'Movimiento lineal', 'descripcion_corta' => 'Rodamientos para movimiento lineal', 'descripcion' => 'Los rodamientos lineales son piezas mecánicas que permiten a una máquina mover objetos en línea recta con un esfuerzo muy bajo. Funcionan guiando un carro sobre un riel o eje mediante pequeñas bolitas o rodillos. Esto reduce el desgaste y permite movimientos suaves y exactos.'],

            // Retenes, Sellos y O-rings
            ['producto' => 'Retenes, Sellos y O-rings', 'nombre' => 'Retenes', 'uso' => 'Sellado de ejes', 'descripcion_corta' => 'Elementos de sellado para ejes rotativos', 'descripcion' => 'Los retenes para sellado son piezas que cierran los espacios entre piezas fijas y móviles. Retienen los lubricantes (aceite o grasa) dentro de las máquinas. También frenan la entrada de polvo y agua. Se usan mucho en motores, cajas de cambios y ruedas.'],
            ['producto' => 'Retenes, Sellos y O-rings', 'nombre' => 'O-Rings', 'uso' => 'Juntas tóricas', 'descripcion_corta' => 'Juntas tóricas para sellado estático y dinámico', 'descripcion' => 'Un o-ring (o junta tórica) es un anillo en forma de rosquilla con sección transversal redonda. Hecho de materiales elásticos, se coloca en una ranura y se comprime al unir dos piezas. Actúa como barrera, bloqueando el paso y evitando fugas de líquidos o gases.'],
            ['producto' => 'Retenes, Sellos y O-rings', 'nombre' => 'Sellos Hidráulicos', 'uso' => 'Sistemas hidráulicos', 'descripcion_corta' => 'Sellos para sistemas hidráulicos', 'descripcion' => 'Los sellos hidráulicos son anillos de caucho o plástico. Actúan como tapones herméticos. Su objetivo es evitar que el aceite o líquido se escape entre las partes de una máquina'],
            ['producto' => 'Retenes, Sellos y O-rings', 'nombre' => 'Sellos Neumáticos', 'uso' => 'Sistemas neumáticos', 'descripcion_corta' => 'Sellos para sistemas neumáticos', 'descripcion' => 'Los sellos neumáticos son componentes de goma o plástico que retienen el aire comprimido en equipos como cilindros o compresores. Su función es evitar fugas, mantener la fuerza del aire y proteger el sistema contra la suciedad.'],

            // Bandas Transportadoras Pesadas
            ['producto' => 'Bandas Transportadoras Pesadas', 'nombre' => 'Bandas Lisas', 'uso' => 'Cargas pesadas', 'descripcion_corta' => 'Bandas para cargas pesadas, minería e industria', 'descripcion' => 'Las bandas transportadoras lisas son cintas planas sin relieves. Mueven productos de un punto a otro. Son la opción más común en fábricas. Funcionan bien en superficies planas o con poca inclinación (hasta 20°).'],
            ['producto' => 'Bandas Transportadoras Pesadas', 'nombre' => 'Bandas Nervadas', 'uso' => 'Cargas pesadas', 'descripcion_corta' => 'Bandas para cargas pesadas, minería e industria', 'descripcion' => 'Las bandas transportadoras nervadas tienen relieves en su superficie, como tacos o crestas. Estos relieves evitan que el material se resbale o se caiga. Permiten subir productos con inclinaciones muy altas (hasta de 45º) y son ideales para cargar productos sueltos, cajas o alimentos.'],
            ['producto' => 'Bandas Transportadoras Pesadas', 'nombre' => 'Bandas Verticales', 'uso' => 'Cargas pesadas', 'descripcion_corta' => 'Bandas para cargas pesadas, minería e industria', 'descripcion' => 'Las bandas transportadoras verticales mueven objetos automáticamente entre diferentes niveles o pisos. Funcionan como un elevador continuo de carga. Su diseño ahorra espacio en las fábricas.'],
            ['producto' => 'Bandas Transportadoras Pesadas', 'nombre' => 'Bandas con Bordes', 'uso' => 'Cargas pesadas', 'descripcion_corta' => 'Bandas para cargas pesadas, minería e industria', 'descripcion' => 'Las bandas transportadoras con bordes contienen barreras físicas o sellos laterales que evitan que el material se caiga durante el traslado. Son clave para subir productos en ángulo o mover materiales sueltos. Existen dos tipos principales de bordes según su fabricación: cortados o moldeados.'],
            ['producto' => 'Bandas Transportadoras Pesadas', 'nombre' => 'Bandas Corrugadas', 'uso' => 'Cargas pesadas', 'descripcion_corta' => 'Bandas para cargas pesadas, minería e industria', 'descripcion' => 'Las bandas transportadoras corrugadas son cintas industriales con relieves en su superficie. Estos relieves mejoran el agarre. Están diseñadas para mover productos frágiles o cargas inclinadas. Evitan que la mercancía ruede o resbale hacia atrás.'],

            // Bandas Transportadoras Livianas
            ['producto' => 'Bandas Transportadoras Livianas', 'nombre' => 'Bandas Sintenticas', 'uso' => 'Industria ligera', 'descripcion_corta' => 'Bandas para industria ligera', 'descripcion' => 'Las bandas transportadoras sintéticas son sistemas de movimiento continuo formados por capas de tela unidas con plásticos como PVC o poliuretano mediante calor. Son muy flexibles, resistentes a la abrasión y fáciles de limpiar. Se usan mucho en alimentos, medicinas y paquetería gracias a sus características higiénicas.'],
            ['producto' => 'Bandas Transportadoras Livianas', 'nombre' => 'Bandas Modulares', 'uso' => 'Industria ligera', 'descripcion_corta' => 'Bandas para industria ligera', 'descripcion' => 'Una banda transportadora modular es un sistema formado por piezas de plástico unidas entre sí. Estas piezas encajan como bloques de construcción. Se conectan usando varillas largas. Esta unión crea una superficie plana, resistente y flexible que se mueve usando ruedas dentadas.'],
            ['producto' => 'Bandas Transportadoras Livianas', 'nombre' => 'Bandas PTFE', 'uso' => 'Industria ligera', 'descripcion_corta' => 'Bandas para industria ligera', 'descripcion' => 'Las bandas transportadoras de PTFE (politetrafluoroetileno, conocido como Teflón) son cintas de fibra de vidrio recubiertas de resina sintética. Son famosas por su superficie antiadherente y su gran resistencia al calor. Soportan temperaturas extremas de -73 °C hasta 260 °C sin dañarse.'],
            ['producto' => 'Bandas Transportadoras Livianas', 'nombre' => 'Bandas Homogeneas', 'uso' => 'Industria ligera', 'descripcion_corta' => 'Bandas para industria ligera', 'descripcion' => 'Las bandas transportadoras homogéneas son fajas continuas hechas de un solo material sólido, como poliuretano o caucho. A diferencia de las bandas tradicionales, no tienen capas internas (lonas) ni grietas. Esto las hace más seguras, duraderas y fáciles de limpiar.'],
            ['producto' => 'Bandas Transportadoras Livianas', 'nombre' => 'Bandas de Caucho Ligeras', 'uso' => 'Industria ligera', 'descripcion_corta' => 'Bandas para industria ligera', 'descripcion' => 'Las bandas transportadoras de caucho ligeras son cintas flexibles hechas de capas de tela (como poliéster) recubiertas de caucho. Mueven materiales de peso bajo o mediano en distancias cortas. Pesan poco y son fáciles de doblar. Estas bandas se usan mucho en agricultura, logística y empaque.'],

            // Cadenas
            ['producto' => 'Cadenas', 'nombre' => 'Cadenas de Rodillos de Precisión', 'uso' => 'Transmisión', 'descripcion_corta' => 'Cadenas para transmisión de potencia', 'descripcion' => 'Las cadenas de rodillos de precisión son piezas mecánicas que transmiten fuerza entre ejes. Usan eslabones metálicos y pequeños cilindros rodantes que engranan en ruedas dentadas. Son vitales en industrias y vehículos, ya que garantizan un movimiento silencioso y sin pérdidas de energía.'],
            ['producto' => 'Cadenas', 'nombre' => 'Cadenas de Acero Inoxidable', 'uso' => 'Resistentes', 'descripcion_corta' => 'Cadenas resistentes a la corrosión', 'descripcion' => 'Las cadenas de acero inoxidable son tiras de eslabones de metal muy fuertes. No se oxidan ni se manchan. Son una mezcla de hierro, cromo y otros metales. El cromo forma una capa invisible que las protege del agua y del clima. Son muy duraderas y seguras para la piel.'],
            ['producto' => 'Cadenas', 'nombre' => 'Cadenas de Transmisión', 'uso' => 'Industrial', 'descripcion_corta' => 'Cadenas para transmisión industrial', 'descripcion' => 'Una cadena de transmisión es un mecanismo que transfiere energía mecánica y movimiento entre dos o más ejes. Consiste en una serie de eslabones metálicos que se engranan con ruedas dentadas (llamadas piñones). Este sistema evita que la cadena resbale, lo que asegura una fuerza exacta y constante.'],
            ['producto' => 'Cadenas', 'nombre' => 'Cadenas con Transportador', 'uso' => 'Transporte', 'descripcion_corta' => 'Cadenas para sistemas de transporte', 'descripcion' => 'Los transportadores de cadena son sistemas industriales que usan eslabones metálicos continuos para mover productos pesados. Un motor gira una rueda. La rueda tira de la cadena. La cadena arrastra la carga. Son muy fuertes. Mueven cosas grandes como palés donde las cintas de goma fallan.'],
            ['producto' => 'Cadenas', 'nombre' => 'Cadenas Agrícolas', 'uso' => 'Agrícola', 'descripcion_corta' => 'Cadenas para maquinaria agrícola', 'descripcion' => 'Las cadenas agrícolas tienen dos significados. En las máquinas, son piezas de metal o plástico que mueven partes de los equipos. En los negocios, son todas las etapas por las que pasa un cultivo desde la granja hasta tu mesa.'],

            // Poleas
            ['producto' => 'Poleas', 'nombre' => 'Poleas en V de Taladro Cónico y Cilíndrico', 'uso' => 'Correas en V', 'descripcion_corta' => 'Poleas para correas en V', 'descripcion' => 'Las poleas en V para taladro transmiten el movimiento del motor al husillo mediante una correa trapezoidal. Los términos cónicas y cilindricas describen cómo se fija la polea al eje.'],
            ['producto' => 'Poleas', 'nombre' => 'Poleas Sincrónicas', 'uso' => 'Correas dentadas', 'descripcion_corta' => 'Poleas para correas dentadas', 'descripcion' => 'Las poleas sincrónicas (o dentadas) son ruedas con ranuras que transmiten fuerza mediante el acoplamiento positivo. Sus dientes encajan perfectamente con los de una correa especial. No usan fricción. Esto garantiza una sincronización exacta, cero deslizamientos y máxima eficiencia.'],
            ['producto' => 'Poleas', 'nombre' => 'Poleas MI-Lock', 'uso' => 'Sistema MI-Lock', 'descripcion_corta' => 'Poleas con sistema de bloqueo MI-Lock', 'descripcion' => 'Las poleas Mi-Lock son componentes mecánicos industriales de transmisión de potencia. Destacan por su sistema de bloqueo cónico sin chavetero, que une la polea al eje mediante presión. Esto elimina la necesidad de ranuras y tornillos. Son duraderas, silenciosas y evitan el desgaste.'],

            // Piñones
            ['producto' => 'Piñones', 'nombre' => 'Piñones de taladro cónico', 'uso' => 'Ajuste cónico', 'descripcion_corta' => 'Piñones con ajuste cónico', 'descripcion' => 'Los piñones de taladro cónico son ruedas dentadas en forma de cono que transfieren la fuerza de giro y el movimiento entre ejes que se cruzan. Se usan mucho en taladros manuales (de pecho o berbiquí) para cambiar la dirección del giro 90° y aumentar la velocidad de la broca.'],
            ['producto' => 'Piñones', 'nombre' => 'Piñones con agujero piloto', 'uso' => 'Mecanizado', 'descripcion_corta' => 'Piñones para mecanizado personalizado', 'descripcion' => 'Los piñones con agujero piloto (también llamados barrenos piloto o pilot bore) son ruedas dentadas que cuentan con un orificio central pequeño y preperforado. Este agujero no está listo para instalarse en una máquina. Sirve como guía para que un tornero lo perfore al tamaño exacto de tu eje.'],
            ['producto' => 'Piñones', 'nombre' => 'Piñones simples de taladro cónico para 2 cadenas', 'uso' => 'Transmisión doble', 'descripcion_corta' => 'Piñones dobles para transmisión', 'descripcion' => 'Los piñones simples de taladro cónico para dos cadenas son ruedas dentadas dobles diseñadas para alojar dos cadenas simples paralelas. Usan un sistema de casquillo cónico para un agarre firme. Esto elimina el juego y hace que el montaje y desmontaje sean muy rápidos y sencillos.'],

            // Niples, Conexiones y Conectores
            ['producto' => 'Niples, Conexiones y Conectores', 'nombre' => 'Niples Hidráulicos', 'uso' => 'Hidráulicos', 'descripcion_corta' => 'Conexiones para sistemas hidráulicos', 'descripcion' => 'Un niple hidráulico es un tubo corto con roscas en ambos extremos. Sirve para unir dos tuberías o mangueras en un sistema hidráulico, que es un mecanismo que usa aceite u otro líquido a presión para mover maquinaria. Su función principal es transmitir esta fuerza con seguridad y sin fugas.'],
            ['producto' => 'Niples, Conexiones y Conectores', 'nombre' => 'Niples de Cobre', 'uso' => 'Cobre', 'descripcion_corta' => 'Conexiones de cobre para diversas aplicaciones', 'descripcion' => 'Los niples de cobre son segmentos cortos de tubo que sirven para conectar dos accesorios de tubería o extender un sistema. Son muy resistentes al calor y a la corrosión, por lo que se usan mucho en agua, gas y aire acondicionado. A menudo se sueldan y garantizan una unión fuerte.'],
            ['producto' => 'Niples, Conexiones y Conectores', 'nombre' => 'Conexiones Rápidas', 'uso' => 'Acople rápido', 'descripcion_corta' => 'Conexiones de acople rápido', 'descripcion' => 'Las conexiones rápidas son accesorios mecánicos que unen tuberías o mangueras en segundos sin usar herramientas. Se componen de dos partes: el macho (que se inserta) y la hembra (que bloquea y sella). Permiten conectar y desconectar sistemas de agua, aire o aceite de forma fácil y sin fugas.'],
            ['producto' => 'Niples, Conexiones y Conectores', 'nombre' => 'Adaptadores', 'uso' => 'Adaptación', 'descripcion_corta' => 'Adaptadores para diferentes configuraciones', 'descripcion' => 'Los adaptadores son piezas clave que unen mangueras entre sí o las conectan a tuberías, llaves y equipos. Evitan fugas y mantienen la presión.'],
            ['producto' => 'Niples, Conexiones y Conectores', 'nombre' => 'Conectores Rápidos', 'uso' => 'Conexión rápida', 'descripcion_corta' => 'Conectores para conexión rápida', 'descripcion' => 'Los conectores rápidos (o racores) permiten unir mangueras, herramientas y equipos de aire comprimido al instante. No necesitas herramientas para conectarlos. Ahorran tiempo, evitan fugas de aire y soportan alta presión gracias a sus sellos internos.'],

            // Cilindros
            ['producto' => 'Cilindros', 'nombre' => 'Cilindros Neumáticos', 'uso' => 'Neumáticos', 'descripcion_corta' => 'Cilindros para sistemas neumáticos', 'descripcion' => 'Los cilindros neumáticos son dispositivos que transforman la energía del aire comprimido en movimiento mecánico lineal. Se usan mucho en la industria para mover, levantar o empujar objetos. Funcionan como una jeringa: el aire empuja una pieza interna, haciendo que una barra salga o entre.'],
            ['producto' => 'Cilindros', 'nombre' => 'Cilindros HTR (Tirantes)', 'uso' => 'Tirantes', 'descripcion_corta' => 'Cilindros con diseño de tirantes', 'descripcion' => 'Los cilindros de tirantes (conocidos como HTR) son componentes mecánicos que usan varillas de acero roscadas para unir las tapas de los extremos al cuerpo del cilindro. Su diseño estandarizado permite un fácil mantenimiento. Son ideales para uso industrial en prensas, maquinaria agrícola y equipos de manipulación de materiales.'],
            ['producto' => 'Cilindros', 'nombre' => 'Cilindros HCW (Patentado)', 'uso' => 'Patentado', 'descripcion_corta' => 'Cilindros con diseño patentado', 'descripcion' => 'Los cilindros HCW son actuadores lineales soldados de doble efecto diseñados para maquinaria industrial. Su nombre alude a los cilindros soldados con extremos de horquilla ajustables (Clevis Welded). Su diseño optimizado maneja grandes cargas en espacios pequeños.'],

            // Cangilones
            ['producto' => 'Cangilones', 'nombre' => 'Cangilones HD Stax (Heavy Duty)', 'uso' => 'Alta resistencia', 'descripcion_corta' => 'Cangilones de alta resistencia', 'descripcion' => 'Los cangilones HD-STAX son recipientes de plástico para elevadores de cangilones. Mueven materiales a granel verticalmente. Son muy populares en la agricultura y la industria. Su diseño "Heavy Duty" (servicio pesado) permite soportar trabajos duros y desgastantes.'],
            ['producto' => 'Cangilones', 'nombre' => 'Cangilones de Nylon', 'uso' => 'Ligeros', 'descripcion_corta' => 'Cangilones ligeros de nylon', 'descripcion' => 'Los cangilones de nylon son recipientes plásticos que se instalan en cintas o cadenas para elevar materiales verticalmente. Son famosos por su gran fuerza y resistencia.'],
            ['producto' => 'Cangilones', 'nombre' => 'Cangilones de Poliuretano', 'uso' => 'Resistentes', 'descripcion_corta' => 'Cangilones resistentes al desgaste', 'descripcion' => 'Los cangilones de poliuretano son recipientes flexibles y ultrarresistentes utilizados en elevadores industriales para cargar y transportar materiales sólidos a granel. Funcionan como cucharas montadas en bandas móviles. Destacan por su extrema resistencia a la abrasión (desgaste por fricción) y su flexibilidad superior al metal o al plástico común.'],
            ['producto' => 'Cangilones', 'nombre' => 'Pernos', 'uso' => 'Fijación', 'descripcion_corta' => 'Pernos para fijación de cangilones', 'descripcion' => 'Los pernos para cangilones (también conocidos como pernos de elevador) son elementos de fijación especializados diseñados para unir de forma segura los cangilones a las bandas o cadenas transportadoras. Evitan que la correa se rompa o resbale durante la operación.'],
            ['producto' => 'Cangilones', 'nombre' => 'Grapas de Empalme Mecánico', 'uso' => 'Unión', 'descripcion_corta' => 'Grapas para unión de bandas', 'descripcion' => 'Las grapas para elevadores de cangilones son un tipo de empalme mecánico usado para unir los extremos de una banda transportadora. Permiten crear una banda continua. A la vez, permiten desarmar la unión fácil y rápidamente para hacer reparaciones o ajustes.'],

            // Cardanes
            ['producto' => 'Cardanes', 'nombre' => 'Cardanes Agrícolas', 'uso' => 'Agrícola', 'descripcion_corta' => 'Cardanes para maquinaria agrícola', 'descripcion' => 'Un cardán agrícola es una barra de transmisión. Lleva la fuerza y el movimiento de rotación desde el tractor hasta la maquinaria (como una desbrozadora o segadora). Funciona como una articulación. Permite que el tractor y el apero giren y se muevan sobre terreno irregular sin romperse.'],

            // Cajas de Comandos
            ['producto' => 'Cajas de Comandos', 'nombre' => 'Caja de Comando de 1 Palanca', 'uso' => '1 Palanca', 'descripcion_corta' => 'Caja de comando con una palanca', 'descripcion' => 'Una caja de comandos de una palanca es un dispositivo mecánico o hidráulico que controla dos acciones clave con un solo mango. Dependiendo del equipo, regula el flujo de aceite para mover maquinaria pesada (como grúas) o controla de forma simultánea la marcha y la aceleración en motores marinos.'],
            ['producto' => 'Cajas de Comandos', 'nombre' => 'Caja de Comandos de 2 Palancas', 'uso' => '2 Palancas', 'descripcion_corta' => 'Caja de comando con dos palancas', 'descripcion' => 'Una caja de comandos de 2 palancas es un dispositivo que permite controlar dos funciones mecánicas o hidráulicas desde un solo lugar. Por ejemplo, en maquinarias, una palanca sube y baja un brazo, mientras que la otra abre y cierra una pinza.'],
            ['producto' => 'Cajas de Comandos', 'nombre' => 'Caja de Comandos de 3 Palancas', 'uso' => '3 Palancas', 'descripcion_corta' => 'Caja de comando con tres palancas', 'descripcion' => 'Una caja de comandos de 3 palancas es un dispositivo hidráulico usado para controlar maquinaria pesada. Permite dirigir el flujo de aceite para activar tres movimientos independientes. Las palancas se mueven a mano para subir, bajar o girar partes de equipos como grúas o tractores.'],
            ['producto' => 'Cajas de Comandos', 'nombre' => 'Caja de Comandos de 4 Palancas', 'uso' => '4 Palancas', 'descripcion_corta' => 'Caja de comando con cuatro palancas', 'descripcion' => 'Una caja de comandos de 4 palancas es un dispositivo que controla sistemas hidráulicos. Permite dirigir el aceite a presión hacia diferentes cilindros o motores. Cada palanca opera una función independiente. Se usa mucho en grúas, montacargas, maquinaria agrícola e hidroelevadores.'],

            // Abrazaderas
            ['producto' => 'Abrazaderas', 'nombre' => 'Abrazaderas Galvanizadas', 'uso' => 'Galvanizadas', 'descripcion_corta' => 'Abrazaderas con recubrimiento galvanizado', 'descripcion' => 'Una abrazadera galvanizada es una pieza de metal resistente que sirve para sujetar y asegurar tuberías, cables o mangueras. Está hecha de acero y recubierta con zinc para evitar la oxidación. Esto permite usarla en exteriores o lugares húmedos sin que se dañe.'],
            ['producto' => 'Abrazaderas', 'nombre' => 'Abrazaderas Inoxidables', 'uso' => 'Inoxidables', 'descripcion_corta' => 'Abrazaderas de acero inoxidable', 'descripcion' => 'Las abrazaderas de acero inoxidable son mecanismos de sujeción. Se usan para fijar, unir o soportar tuberías y mangueras. Aplican una fuerza de presión uniforme. Son muy duraderas porque resisten el óxido y los cambios de temperatura.'],
            ['producto' => 'Abrazaderas', 'nombre' => 'Abrazaderas de Tornillo', 'uso' => 'Tornillo', 'descripcion_corta' => 'Abrazaderas con sistema de tornillo', 'descripcion' => 'Las abrazaderas de tornillo son dispositivos que unen o sujetan objetos firmemente usando un mecanismo de tornillo. En fontanería y automoción, sellan mangueras. En carpintería, sostienen piezas juntas de forma temporal. Son reutilizables, ajustables y ofrecen una gran fuerza de apriete.'],
            ['producto' => 'Abrazaderas', 'nombre' => 'Abrazaderas de Alambre', 'uso' => 'Alambre', 'descripcion_corta' => 'Abrazaderas de alambre', 'descripcion' => 'Una abrazadera de alambre es un anillo de metal diseñado para sujetar tuberías, cables o mangueras. Aprieta el tubo alrededor de otra pieza usando un tornillo o tuerca. Es ideal para trabajos donde hay baja presión o espacio reducido, ya que no daña los materiales.'],
        ];

        $orden = 1;
        foreach ($categorias as $cat) {
            $producto = Producto::where('nombre', $cat['producto'])->first();

            if (!$producto) {
                $this->command->error("❌ Producto no encontrado: '{$cat['producto']}'");
                continue;
            }

            Categoria::create([
                'producto_id' => $producto->id,
                'nombre' => $cat['nombre'],
                'slug' => Str::slug($cat['nombre']),
                'imagen' => '/default/placeholder.png',
                'uso' => $cat['uso'],
                'descripcion_corta' => $cat['descripcion_corta'],
                'descripcion' => $cat['descripcion'],
                'orden' => $orden++,
                'estado' => 'activo',
            ]);
        }

        $this->command->info("✅ " . count($categorias) . " categorías procesadas");
    }
}
