<?php

namespace App\Filament\Traits;

/**
 * Trait con los 500 iconos más importantes de Font Awesome Free
 * Organizados por categorías para fácil navegación
 *
 * Uso: use HasFontAwesomeIcons; en cualquier Form de Filament
 * Luego: Select::make('icon')->options(self::getFontAwesomeIcons())
 */
trait HasFontAwesomeIcons
{
    /**
     * Obtiene los 500 iconos más importantes de Font Awesome Free
     *
     * @return array
     */
    public static function getFontAwesomeIcons(): array
    {
        return [
            // ══════════════════════════════════════════════════════════
            //  NEGOCIOS Y TRABAJO (40 iconos)
            // ══════════════════════════════════════════════════════════
            'fa-briefcase' => '💼 Maletín (Briefcase)',
            'fa-building' => '🏢 Edificio (Building)',
            'fa-industry' => '🏭 Industria (Industry)',
            'fa-store' => ' Tienda (Store)',
            'fa-store-alt' => '🏪 Tienda Alt (Store Alt)',
            'fa-warehouse' => '🏭 Almacén (Warehouse)',
            'fa-shopping-cart' => '🛒 Carrito (Shopping Cart)',
            'fa-shopping-bag' => '🛍️ Bolsa (Shopping Bag)',
            'fa-shopping-basket' => '🧺 Canasta (Shopping Basket)',
            'fa-box' => '📦 Caja (Box)',
            'fa-box-open' => ' Caja Abierta (Box Open)',
            'fa-boxes' => '📦 Cajas (Boxes)',
            'fa-clipboard' => '📋 Portapapeles (Clipboard)',
            'fa-clipboard-list' => '📋 Lista (Clipboard List)',
            'fa-clipboard-check' => '📋 Verificado (Clipboard Check)',
            'fa-file' => ' Archivo (File)',
            'fa-file-alt' => '📄 Archivo Alt (File Alt)',
            'fa-file-invoice' => '📄 Factura (File Invoice)',
            'fa-file-invoice-dollar' => ' Factura $ (File Invoice $)',
            'fa-file-contract' => '📄 Contrato (File Contract)',
            'fa-file-signature' => ' Firma (File Signature)',
            'fa-folder' => '📁 Carpeta (Folder)',
            'fa-folder-open' => '📂 Carpeta Abierta (Folder Open)',
            'fa-archive' => '️ Archivo (Archive)',
            'fa-chart-bar' => '📊 Gráfico Barras (Chart Bar)',
            'fa-chart-line' => '📈 Gráfico Línea (Chart Line)',
            'fa-chart-pie' => '🥧 Gráfico Pastel (Chart Pie)',
            'fa-chart-area' => ' Gráfico Área (Chart Area)',
            'fa-balance-scale' => '️ Balanza (Balance Scale)',
            'fa-calculator' => '🧮 Calculadora (Calculator)',
            'fa-coins' => '🪙 Monedas (Coins)',
            'fa-hand-holding-usd' => '💵 Mano con $ (Hand Holding USD)',
            'fa-money-bill' => '💵 Billete (Money Bill)',
            'fa-money-bill-wave' => '💵 Billete Onda (Money Bill Wave)',
            'fa-credit-card' => '💳 Tarjeta Crédito (Credit Card)',
            'fa-wallet' => '👛 Cartera (Wallet)',
            'fa-piggy-bank' => '🐷 Alcancía (Piggy Bank)',
            'fa-receipt' => '🧾 Recibo (Receipt)',
            'fa-tag' => '🏷️ Etiqueta (Tag)',
            'fa-tags' => '🏷️ Etiquetas (Tags)',

            // ═══════════════════════════════════════════════════════════
            //  HERRAMIENTAS Y CONFIGURACIÓN (35 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-wrench' => '🔧 Llave (Wrench)',
            'fa-tools' => '🛠️ Herramientas (Tools)',
            'fa-hammer' => '🔨 Martillo (Hammer)',
            'fa-screwdriver' => '🪛 Destornillador (Screwdriver)',
            'fa-cog' => '⚙️ Engranaje (Cog)',
            'fa-cogs' => '️ Engranajes (Cogs)',
            'fa-sliders-h' => '️ Sliders (Sliders H)',
            'fa-database' => '💾 Base de Datos (Database)',
            'fa-server' => '🖥️ Servidor (Server)',
            'fa-hdd' => '💿 Disco Duro (HDD)',
            'fa-microchip' => ' Microchip (Microchip)',
            'fa-laptop' => '💻 Laptop (Laptop)',
            'fa-desktop' => '🖥️ Escritorio (Desktop)',
            'fa-mobile-alt' => '📱 Móvil (Mobile Alt)',
            'fa-tablet-alt' => ' Tablet (Tablet Alt)',
            'fa-keyboard' => '⌨️ Teclado (Keyboard)',
            'fa-mouse' => '🖱️ Mouse (Mouse)',
            'fa-print' => '🖨️ Impresora (Print)',
            'fa-fax' => '📠 Fax (Fax)',
            'fa-camera' => '📷 Cámara (Camera)',
            'fa-camera-retro' => '📷 Cámara Retro (Camera Retro)',
            'fa-video' => '🎥 Video (Video)',
            'fa-film' => '🎬 Película (Film)',
            'fa-broadcast-tower' => '📡 Torre (Broadcast Tower)',
            'fa-satellite' => '🛰️ Satélite (Satellite)',
            'fa-satellite-dish' => '🛰️ Antena (Satellite Dish)',
            'fa-wifi' => '📶 WiFi (WiFi)',
            'fa-bluetooth' => '🔵 Bluetooth (Bluetooth)',
            'fa-bluetooth-b' => '🔵 Bluetooth B (Bluetooth B)',
            'fa-plug' => '🔌 Enchufe (Plug)',
            'fa-battery-full' => '🔋 Batería Llena (Battery Full)',
            'fa-battery-half' => '🔋 Batería Media (Battery Half)',
            'fa-battery-quarter' => '🔋 Batería Baja (Battery Quarter)',
            'fa-battery-empty' => '🔋 Batería Vacía (Battery Empty)',
            'fa-power-off' => '⏻ Apagar (Power Off)',

            // ═══════════════════════════════════════════════════════════
            // 👥 USUARIOS Y PERSONAS (25 iconos)
            // ══════════════════════════════════════════════════════════
            'fa-user' => '👤 Usuario (User)',
            'fa-user-alt' => '👤 Usuario Alt (User Alt)',
            'fa-users' => '👥 Usuarios (Users)',
            'fa-user-friends' => '👥 Amigos (User Friends)',
            'fa-user-plus' => '👤➕ Agregar Usuario (User Plus)',
            'fa-user-minus' => '👤➖ Quitar Usuario (User Minus)',
            'fa-user-check' => '👤✓ Verificado (User Check)',
            'fa-user-times' => '✕ Eliminar Usuario (User Times)',
            'fa-user-cog' => '👤⚙️ Config Usuario (User Cog)',
            'fa-user-edit' => '👤✏️ Editar Usuario (User Edit)',
            'fa-user-shield' => '👤🛡️ Usuario Seguro (User Shield)',
            'fa-user-lock' => '👤🔒 Usuario Bloqueado (User Lock)',
            'fa-user-graduate' => '👤🎓 Graduado (User Graduate)',
            'fa-user-md' => '👤⚕️ Doctor (User MD)',
            'fa-user-nurse' => '👤⚕️ Enfermera (User Nurse)',
            'fa-id-card' => '🪪 Tarjeta ID (ID Card)',
            'fa-id-badge' => ' Insignia ID (ID Badge)',
            'fa-address-card' => '📇 Tarjeta Dirección (Address Card)',
            'fa-address-book' => '📖 Libro Direcciones (Address Book)',
            'fa-child' => ' Niño (Child)',
            'fa-baby' => '👶 Bebé (Baby)',
            'fa-female' => '♀️ Femenino (Female)',
            'fa-male' => '♂️ Masculino (Male)',
            'fa-wheelchair' => '♿ Silla de Ruedas (Wheelchair)',
            'fa-blind' => ' Ciego (Blind)',

            // ═══════════════════════════════════════════════════════════
            // 💬 COMUNICACIÓN (35 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-envelope' => '✉️ Correo (Envelope)',
            'fa-envelope-open' => '️ Correo Abierto (Envelope Open)',
            'fa-envelope-square' => '✉️ Correo Cuadrado (Envelope Square)',
            'fa-paper-plane' => '✈️ Avión Papel (Paper Plane)',
            'fa-inbox' => '📥 Bandeja Entrada (Inbox)',
            'fa-mail-bulk' => '📬 Correo Masivo (Mail Bulk)',
            'fa-postal' => '📮 Postal (Postal)',
            'fa-phone' => '📞 Teléfono (Phone)',
            'fa-phone-alt' => ' Teléfono Alt (Phone Alt)',
            'fa-phone-square' => '📞 Teléfono Cuadrado (Phone Square)',
            'fa-phone-volume' => '📞 Teléfono Volumen (Phone Volume)',
            'fa-fax' => '📠 Fax (Fax)',
            'fa-comment' => '💬 Comentario (Comment)',
            'fa-comments' => '💬 Comentarios (Comments)',
            'fa-comment-dots' => '💬 Puntos (Comment Dots)',
            'fa-comment-medical' => '💬 Médico (Comment Medical)',
            'fa-comment-slash' => '💬 Tachado (Comment Slash)',
            'fa-sms' => '📱 SMS (SMS)',
            'fa-bullhorn' => '📢 Megáfono (Bullhorn)',
            'fa-bullseye' => ' Diana (Bullseye)',
            'fa-bell' => '🔔 Campana (Bell)',
            'fa-bell-slash' => '🔔 Campana Tachada (Bell Slash)',
            'fa-at' => '@ Arroba (At)',
            'fa-hashtag' => '# Hashtag (Hashtag)',
            'fa-share' => ' Compartir (Share)',
            'fa-share-alt' => '📤 Compartir Alt (Share Alt)',
            'fa-share-square' => ' Compartir Cuadrado (Share Square)',
            'fa-external-link-alt' => ' Enlace Externo (External Link Alt)',
            'fa-link' => ' Enlace (Link)',
            'fa-unlink' => '🔗 Desenlazar (Unlink)',
            'fa-rss' => '📡 RSS (RSS)',
            'fa-rss-square' => '📡 RSS Cuadrado (RSS Square)',
            'fa-globe' => '🌍 Globo (Globe)',
            'fa-globe-americas' => '🌎 Globo Américas (Globe Americas)',
            'fa-globe-europe' => '🌍 Globo Europa (Globe Europe)',

            // ═══════════════════════════════════════════════════════════
            // 🕐 TIEMPO Y CALENDARIO (25 iconos)
            // ══════════════════════════════════════════════════════════
            'fa-clock' => '🕐 Reloj (Clock)',
            'fa-calendar' => '📅 Calendario (Calendar)',
            'fa-calendar-alt' => ' Calendario Alt (Calendar Alt)',
            'fa-calendar-check' => '📅 Verificado (Calendar Check)',
            'fa-calendar-times' => '📅 Cancelado (Calendar Times)',
            'fa-calendar-plus' => ' Agregar (Calendar Plus)',
            'fa-calendar-minus' => ' Quitar (Calendar Minus)',
            'fa-calendar-week' => '📅 Semana (Calendar Week)',
            'fa-calendar-day' => '📅 Día (Calendar Day)',
            'fa-hourglass' => '⏳ Reloj Arena (Hourglass)',
            'fa-hourglass-start' => '⏳ Inicio (Hourglass Start)',
            'fa-hourglass-half' => '⏳ Mitad (Hourglass Half)',
            'fa-hourglass-end' => '⏳ Fin (Hourglass End)',
            'fa-stopwatch' => '⏱️ Cronómetro (Stopwatch)',
            'fa-history' => '🕰️ Historial (History)',
            'fa-redo' => '↻ Rehacer (Redo)',
            'fa-undo' => '↺ Deshacer (Undo)',
            'fa-sync' => '🔄 Sincronizar (Sync)',
            'fa-sync-alt' => '🔄 Sincronizar Alt (Sync Alt)',
            'fa-spinner' => '🌀 Girando (Spinner)',
            'fa-circle-notch' => ' Notch (Circle Notch)',
            'fa-hourglass-full' => ' Lleno (Hourglass Full)',
            'fa-business-time' => '💼 Tiempo Negocio (Business Time)',
            'fa-business-time' => '💼 Tiempo Negocio (Business Time)',
            'fa-mug-hot' => '☕ Taza Caliente (Mug Hot)',
            'fa-coffee' => '☕ Café (Coffee)',

            // ═══════════════════════════════════════════════════════════
            //  UBICACIÓN Y MAPAS (25 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-map-marker-alt' => ' Marcador (Map Marker Alt)',
            'fa-map-marker' => '📍 Marcador (Map Marker)',
            'fa-map' => '🗺️ Mapa (Map)',
            'fa-map-marked' => '🗺️ Marcado (Map Marked)',
            'fa-map-marked-alt' => '🗺️ Marcado Alt (Map Marked Alt)',
            'fa-map-signs' => '🗺️ Señales (Map Signs)',
            'fa-location-arrow' => '📍 Flecha Ubicación (Location Arrow)',
            'fa-compass' => '🧭 Brújula (Compass)',
            'fa-directions' => ' Direcciones (Directions)',
            'fa-road' => '🛣️ Carretera (Road)',
            'fa-route' => '🛣️ Ruta (Route)',
            'fa-street-view' => '️ Vista Calle (Street View)',
            'fa-car' => '🚗 Auto (Car)',
            'fa-taxi' => ' Taxi (Taxi)',
            'fa-bus' => '🚌 Bus (Bus)',
            'fa-truck' => '🚚 Camión (Truck)',
            'fa-truck-moving' => '🚚 Camión Moviendo (Truck Moving)',
            'fa-plane' => '✈️ Avión (Plane)',
            'fa-ship' => '🚢 Barco (Ship)',
            'fa-bicycle' => '🚲 Bicicleta (Bicycle)',
            'fa-motorcycle' => '️ Moto (Motorcycle)',
            'fa-train' => '🚆 Tren (Train)',
            'fa-subway' => ' Metro (Subway)',
            'fa-helicopter' => '🚁 Helicóptero (Helicopter)',
            'fa-rocket' => '🚀 Cohete (Rocket)',

            // ═══════════════════════════════════════════════════════════
            // ️ ALERTAS Y NOTIFICACIONES (30 iconos)
            // ══════════════════════════════════════════════════════════
            'fa-exclamation-circle' => '⚠️ Alerta Círculo (Exclamation Circle)',
            'fa-exclamation-triangle' => '⚠️ Alerta Triángulo (Exclamation Triangle)',
            'fa-exclamation' => ' Exclamación (Exclamation)',
            'fa-question-circle' => '❓ Pregunta Círculo (Question Circle)',
            'fa-question' => '❓ Pregunta (Question)',
            'fa-info-circle' => '️ Info Círculo (Info Circle)',
            'fa-info' => 'ℹ️ Info (Info)',
            'fa-check-circle' => '✅ Check Círculo (Check Circle)',
            'fa-check-square' => '✅ Check Cuadrado (Check Square)',
            'fa-check' => '✓ Check (Check)',
            'fa-times-circle' => ' X Círculo (Times Circle)',
            'fa-times-square' => ' X Cuadrado (Times Square)',
            'fa-times' => '✕ X (Times)',
            'fa-ban' => '🚫 Prohibido (Ban)',
            'fa-bolt' => '⚡ Rayo (Bolt)',
            'fa-fire' => '🔥 Fuego (Fire)',
            'fa-fire-alt' => '🔥 Fuego Alt (Fire Alt)',
            'fa-radiation' => '☢️ Radiación (Radiation)',
            'fa-biohazard' => '☣️ Biohazard (Biohazard)',
            'fa-skull' => '💀 Calavera (Skull)',
            'fa-skull-crossbones' => '️ Calavera Cruzada (Skull Crossbones)',
            'fa-ghost' => '👻 Fantasma (Ghost)',
            'fa-bug' => ' Bicho (Bug)',
            'fa-virus' => '🦠 Virus (Virus)',
            'fa-virus-slash' => '🦠 Virus Tachado (Virus Slash)',
            'fa-shield-virus' => '🛡️ Escudo Virus (Shield Virus)',
            'fa-head-side-mask' => '😷 Mascarilla (Head Side Mask)',
            'fa-head-side-cough' => '🤧 Toser (Head Side Cough)',
            'fa-lungs' => '🫁 Pulmones (Lungs)',
            'fa-hand-holding-medical' => '🩺 Médico (Hand Holding Medical)',

            // ═══════════════════════════════════════════════════════════
            // ➡️ FLECHAS Y DIRECCIÓN (40 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-arrow-right' => '➡️ Flecha Derecha (Arrow Right)',
            'fa-arrow-left' => '⬅️ Flecha Izquierda (Arrow Left)',
            'fa-arrow-up' => '⬆️ Flecha Arriba (Arrow Up)',
            'fa-arrow-down' => '⬇️ Flecha Abajo (Arrow Down)',
            'fa-arrow-alt-circle-right' => '➡️ Círculo Derecha (Arrow Alt Circle Right)',
            'fa-arrow-alt-circle-left' => '⬅️ Círculo Izquierda (Arrow Alt Circle Left)',
            'fa-arrow-alt-circle-up' => '️ Círculo Arriba (Arrow Alt Circle Up)',
            'fa-arrow-alt-circle-down' => '⬇️ Círculo Abajo (Arrow Alt Circle Down)',
            'fa-chevron-right' => '› Chevron Derecha (Chevron Right)',
            'fa-chevron-left' => '‹ Chevron Izquierda (Chevron Left)',
            'fa-chevron-up' => '› Chevron Arriba (Chevron Up)',
            'fa-chevron-down' => '› Chevron Abajo (Chevron Down)',
            'fa-chevron-circle-right' => '› Círculo Derecha (Chevron Circle Right)',
            'fa-chevron-circle-left' => '‹ Círculo Izquierda (Chevron Circle Left)',
            'fa-chevron-circle-up' => '› Círculo Arriba (Chevron Circle Up)',
            'fa-chevron-circle-down' => '› Círculo Abajo (Chevron Circle Down)',
            'fa-angle-right' => '› Ángulo Derecha (Angle Right)',
            'fa-angle-left' => '‹ Ángulo Izquierda (Angle Left)',
            'fa-angle-up' => '› Ángulo Arriba (Angle Up)',
            'fa-angle-down' => '› Ángulo Abajo (Angle Down)',
            'fa-angle-double-right' => '» Doble Ángulo Derecha (Angle Double Right)',
            'fa-angle-double-left' => '« Doble Ángulo Izquierda (Angle Double Left)',
            'fa-angle-double-up' => '» Doble Ángulo Arriba (Angle Double Up)',
            'fa-angle-double-down' => '» Doble Ángulo Abajo (Angle Double Down)',
            'fa-caret-right' => '▸ Caret Derecha (Caret Right)',
            'fa-caret-left' => ' Caret Izquierda (Caret Left)',
            'fa-caret-up' => '▴ Caret Arriba (Caret Up)',
            'fa-caret-down' => '▾ Caret Abajo (Caret Down)',
            'fa-caret-square-right' => ' Cuadrado Derecha (Caret Square Right)',
            'fa-caret-square-left' => '◂ Cuadrado Izquierda (Caret Square Left)',
            'fa-caret-square-up' => '▴ Cuadrado Arriba (Caret Square Up)',
            'fa-caret-square-down' => '▾ Cuadrado Abajo (Caret Square Down)',
            'fa-long-arrow-alt-right' => '➡️ Flecha Larga Derecha (Long Arrow Alt Right)',
            'fa-long-arrow-alt-left' => '⬅️ Flecha Larga Izquierda (Long Arrow Alt Left)',
            'fa-long-arrow-alt-up' => '⬆️ Flecha Larga Arriba (Long Arrow Alt Up)',
            'fa-long-arrow-alt-down' => '⬇️ Flecha Larga Abajo (Long Arrow Alt Down)',
            'fa-exchange-alt' => ' Intercambio (Exchange Alt)',
            'fa-random' => '🔀 Aleatorio (Random)',
            'fa-redo-alt' => '↻ Rehacer Alt (Redo Alt)',
            'fa-undo-alt' => '↺ Deshacer Alt (Undo Alt)',

            // ═══════════════════════════════════════════════════════════
            // 🔍 ACCIONES Y BÚSQUEDA (30 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-search' => ' Buscar (Search)',
            'fa-search-plus' => '🔍➕ Zoom In (Search Plus)',
            'fa-search-minus' => '🔍➖ Zoom Out (Search Minus)',
            'fa-search-dollar' => '🔍💰 Buscar $ (Search Dollar)',
            'fa-search-location' => '🔍📍 Buscar Ubicación (Search Location)',
            'fa-filter' => '🔽 Filtro (Filter)',
            'fa-sort' => '↕️ Ordenar (Sort)',
            'fa-sort-up' => '⬆️ Ordenar Ascendente (Sort Up)',
            'fa-sort-down' => '⬇️ Ordenar Descendente (Sort Down)',
            'fa-sort-alpha-up' => '🔤 Ordenar A-Z (Sort Alpha Up)',
            'fa-sort-alpha-down' => '🔤 Ordenar Z-A (Sort Alpha Down)',
            'fa-sort-numeric-up' => '🔢 Ordenar 1-9 (Sort Numeric Up)',
            'fa-sort-numeric-down' => '🔢 Ordenar 9-1 (Sort Numeric Down)',
            'fa-download' => '️ Descargar (Download)',
            'fa-upload' => '⬆️ Subir (Upload)',
            'fa-cloud-download-alt' => '☁️⬇️ Nube Descargar (Cloud Download Alt)',
            'fa-cloud-upload-alt' => '☁️️ Nube Subir (Cloud Upload Alt)',
            'fa-save' => '💾 Guardar (Save)',
            'fa-trash' => '🗑️ Basura (Trash)',
            'fa-trash-alt' => '️ Basura Alt (Trash Alt)',
            'fa-trash-restore' => '🗑️♻️ Restaurar (Trash Restore)',
            'fa-trash-restore-alt' => '🗑️♻️ Restaurar Alt (Trash Restore Alt)',
            'fa-edit' => '✏️ Editar (Edit)',
            'fa-pen' => '🖊️ Pluma (Pen)',
            'fa-pen-alt' => '🖊️ Pluma Alt (Pen Alt)',
            'fa-pencil-alt' => '✏️ Lápiz Alt (Pencil Alt)',
            'fa-paint-brush' => '🖌️ Pincel (Paint Brush)',
            'fa-paint-roller' => '🎨 Rodillo (Paint Roller)',
            'fa-eraser' => '🧽 Borrador (Eraser)',
            'fa-copy' => ' Copiar (Copy)',

            // ═══════════════════════════════════════════════════════════
            // 🔒 SEGURIDAD Y ACCESO (25 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-lock' => '🔒 Candado (Lock)',
            'fa-lock-open' => ' Candado Abierto (Lock Open)',
            'fa-unlock' => '🔓 Desbloquear (Unlock)',
            'fa-unlock-alt' => '🔓 Desbloquear Alt (Unlock Alt)',
            'fa-key' => ' Llave (Key)',
            'fa-fingerprint' => '🔐 Huella Digital (Fingerprint)',
            'fa-shield-alt' => '🛡️ Escudo Alt (Shield Alt)',
            'fa-shield-alt' => '️ Escudo Alt (Shield Alt)',
            'fa-user-shield' => '👤️ Usuario Escudo (User Shield)',
            'fa-user-lock' => '👤 Usuario Bloqueado (User Lock)',
            'fa-eye' => '👁️ Ojo (Eye)',
            'fa-eye-slash' => '🙈 Ojo Tachado (Eye Slash)',
            'fa-user-secret' => '🕵️ Usuario Secreto (User Secret)',
            'fa-mask' => '🎭 Mascarilla (Mask)',
            'fa-user-ninja' => '🥷 Ninja (User Ninja)',
            'fa-spy' => '️ Espía (Spy)',
            'fa-id-card-alt' => '🪪 ID Alt (ID Card Alt)',
            'fa-passport' => '🛂 Pasaporte (Passport)',
            'fa-sign-in-alt' => ' Iniciar Sesión (Sign In Alt)',
            'fa-sign-out-alt' => '🚪 Cerrar Sesión (Sign Out Alt)',
            'fa-door-open' => '🚪 Puerta Abierta (Door Open)',
            'fa-door-closed' => '🚪 Puerta Cerrada (Door Closed)',
            'fa-user-lock' => '👤🔒 Usuario Bloqueado (User Lock)',
            'fa-user-shield' => '👤🛡️ Usuario Escudo (User Shield)',
            'fa-user-tie' => '👤👔 Usuario Corbata (User Tie)',

            // ══════════════════════════════════════════════════════════
            // ⭐ ÉXITO, FAVORITOS Y RECONOCIMIENTO (30 iconos)
            // ══════════════════════════════════════════════════════════
            'fa-star' => '⭐ Estrella (Star)',
            'fa-star-half' => '⭐ Media Estrella (Star Half)',
            'fa-star-half-alt' => '⭐ Media Estrella Alt (Star Half Alt)',
            'fa-certificate' => '📜 Certificado (Certificate)',
            'fa-award' => '🏆 Premio (Award)',
            'fa-medal' => ' Medalla (Medal)',
            'fa-trophy' => '🏆 Trofeo (Trophy)',
            'fa-crown' => '👑 Corona (Crown)',
            'fa-gem' => '💎 Gema (Gem)',
            'fa-heart' => '❤️ Corazón (Heart)',
            'fa-heart-broken' => '💔 Corazón Roto (Heart Broken)',
            'fa-thumbs-up' => '👍 Me Gusta (Thumbs Up)',
            'fa-thumbs-down' => ' No Me Gusta (Thumbs Down)',
            'fa-smile' => '😊 Sonrisa (Smile)',
            'fa-smile-beam' => '😊 Sonrisa Brillante (Smile Beam)',
            'fa-smile-wink' => '😉 Guiño (Smile Wink)',
            'fa-laugh' => '😂 Risa (Laugh)',
            'fa-laugh-beam' => ' Risa Brillante (Laugh Beam)',
            'fa-laugh-squint' => '😆 Risa Ojos Cerrados (Laugh Squint)',
            'fa-laugh-wink' => '😜 Risa Guiño (Laugh Wink)',
            'fa-grin' => '😁 Sonrisa Grande (Grin)',
            'fa-grin-beam' => '😁 Sonrisa Brillante (Grin Beam)',
            'fa-grin-hearts' => '😍 Sonrisa Corazones (Grin Hearts)',
            'fa-grin-stars' => '🤩 Sonrisa Estrellas (Grin Stars)',
            'fa-grin-tongue' => '😛 Sonrisa Lengua (Grin Tongue)',
            'fa-grin-tongue-wink' => '😜 Sonrisa Lengua Guiño (Grin Tongue Wink)',
            'fa-grin-wink' => '😜 Sonrisa Guiño (Grin Wink)',
            'fa-kiss' => '😘 Beso (Kiss)',
            'fa-kiss-beam' => '😘 Beso Brillante (Kiss Beam)',
            'fa-kiss-wink-heart' => '😘 Beso Corazón (Kiss Wink Heart)',

            // ═══════════════════════════════════════════════════════════
            //  MULTIMEDIA Y ENTRETENIMIENTO (35 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-music' => '🎵 Música (Music)',
            'fa-microphone' => '🎤 Micrófono (Microphone)',
            'fa-microphone-alt' => '🎤 Micrófono Alt (Microphone Alt)',
            'fa-headphones' => '🎧 Auriculares (Headphones)',
            'fa-headphones-alt' => '🎧 Auriculares Alt (Headphones Alt)',
            'fa-volume-up' => '🔊 Volumen Alto (Volume Up)',
            'fa-volume-down' => '🔉 Volumen Bajo (Volume Down)',
            'fa-volume-mute' => '🔇 Silencio (Volume Mute)',
            'fa-volume-off' => '🔇 Volumen Off (Volume Off)',
            'fa-podcast' => '🎙️ Podcast (Podcast)',
            'fa-radio' => '📻 Radio (Radio)',
            'fa-tv' => '📺 Televisión (TV)',
            'fa-play' => '▶️ Reproducir (Play)',
            'fa-play-circle' => '▶️ Círculo Reproducir (Play Circle)',
            'fa-pause' => '️ Pausar (Pause)',
            'fa-pause-circle' => '⏸️ Círculo Pausar (Pause Circle)',
            'fa-stop' => '⏹️ Detener (Stop)',
            'fa-stop-circle' => '⏹️ Círculo Detener (Stop Circle)',
            'fa-forward' => '⏭️ Adelantar (Forward)',
            'fa-backward' => '️ Retroceder (Backward)',
            'fa-step-forward' => '⏭️ Paso Adelante (Step Forward)',
            'fa-step-backward' => '⏮️ Paso Atrás (Step Backward)',
            'fa-eject' => '️ Expulsar (Eject)',
            'fa-compact-disc' => ' CD (Compact Disc)',
            'fa-vinyl' => '🎵 Vinilo (Vinyl)',
            'fa-gamepad' => ' Control Juego (Gamepad)',
            'fa-dice' => '🎲 Dado (Dice)',
            'fa-dice-d20' => '🎲 D20 (Dice D20)',
            'fa-dice-d6' => '🎲 D6 (Dice D6)',
            'fa-chess' => '♟️ Ajedrez (Chess)',
            'fa-chess-king' => '♔ Rey (Chess King)',
            'fa-chess-queen' => '♕ Reina (Chess Queen)',
            'fa-chess-rook' => '♜ Torre (Chess Rook)',
            'fa-chess-bishop' => '♝ Alfil (Chess Bishop)',
            'fa-chess-knight' => '♞ Caballo (Chess Knight)',

            // ═══════════════════════════════════════════════════════════
            // 🌿 NATURALEZA Y CLIMA (30 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-sun' => '☀️ Sol (Sun)',
            'fa-moon' => ' Luna (Moon)',
            'fa-cloud' => '☁️ Nube (Cloud)',
            'fa-cloud-sun' => ' Nube Sol (Cloud Sun)',
            'fa-cloud-moon' => '🌥️ Nube Luna (Cloud Moon)',
            'fa-cloud-rain' => '🌧️ Lluvia (Cloud Rain)',
            'fa-cloud-showers-heavy' => '🌧️ Lluvia Fuerte (Cloud Showers Heavy)',
            'fa-cloud-snow' => '❄️ Nieve (Cloud Snow)',
            'fa-cloud-meatball' => '🌩️ Tormenta (Cloud Meatball)',
            'fa-cloud-lightning' => '⛈️ Rayo (Cloud Lightning)',
            'fa-smog' => '🌫️ Smog (Smog)',
            'fa-wind' => '💨 Viento (Wind)',
            'fa-tornado' => '️ Tornado (Tornado)',
            'fa-umbrella' => '️ Paraguas (Umbrella)',
            'fa-temperature-high' => '️ Temperatura Alta (Temperature High)',
            'fa-temperature-low' => '️ Temperatura Baja (Temperature Low)',
            'fa-snowflake' => '❄️ Copo Nieve (Snowflake)',
            'fa-snowman' => '⛄ Muñeco Nieve (Snowman)',
            'fa-droplet' => '💧 Gota (Droplet)',
            'fa-water' => '💧 Agua (Water)',
            'fa-leaf' => '🍃 Hoja (Leaf)',
            'fa-seedling' => '🌱 Brote (Seedling)',
            'fa-tree' => ' Árbol (Tree)',
            'fa-palm-tree' => ' Palmera (Palm Tree)',
            'fa-cactus' => '🌵 Cactus (Cactus)',
            'fa-fish' => '🐟 Pez (Fish)',
            'fa-dog' => ' Perro (Dog)',
            'fa-cat' => '🐱 Gato (Cat)',
            'fa-crow' => ' Cuervo (Crow)',
            'fa-spider' => '🕷️ Araña (Spider)',

            // ═══════════════════════════════════════════════════════════
            // 🍕 COMIDA Y BEBIDA (25 iconos)
            // ══════════════════════════════════════════════════════════
            'fa-pizza-slice' => '🍕 Pizza (Pizza Slice)',
            'fa-hamburger' => '🍔 Hamburguesa (Hamburger)',
            'fa-hotdog' => ' Hotdog (Hotdog)',
            'fa-bacon' => '🥓 Tocino (Bacon)',
            'fa-egg' => '🥚 Huevo (Egg)',
            'fa-bread-slice' => '🍞 Pan (Bread Slice)',
            'fa-cheese' => '🧀 Queso (Cheese)',
            'fa-apple-alt' => '🍎 Manzana (Apple Alt)',
            'fa-lemon' => '🍋 Limón (Lemon)',
            'fa-carrot' => ' Zanahoria (Carrot)',
            'fa-pepper-hot' => '🌶️ Chile (Pepper Hot)',
            'fa-ice-cream' => '🍦 Helado (Ice Cream)',
            'fa-candy-cane' => '🍭 Bastón Caramelo (Candy Cane)',
            'fa-cookie' => '🍪 Galleta (Cookie)',
            'fa-cookie-bite' => '🍪 Galleta Mordida (Cookie Bite)',
            'fa-cake-candles' => '🎂 Pastel (Cake Candles)',
            'fa-wine-glass' => '🍷 Copa Vino (Wine Glass)',
            'fa-wine-glass-alt' => '🍷 Copa Vino Alt (Wine Glass Alt)',
            'fa-glass-martini' => '🍸 Martini (Glass Martini)',
            'fa-glass-martini-alt' => '🍸 Martini Alt (Glass Martini Alt)',
            'fa-glass-whiskey' => '🥃 Whiskey (Glass Whiskey)',
            'fa-beer' => '🍺 Cerveza (Beer)',
            'fa-cocktail' => '🍹 Cóctel (Cocktail)',
            'fa-mug-hot' => '☕ Taza Caliente (Mug Hot)',
            'fa-coffee' => '☕ Café (Coffee)',

            // ═══════════════════════════════════════════════════════════
            //  SALUD Y MEDICINA (25 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-heartbeat' => ' Latido (Heartbeat)',
            'fa-pulse' => '💓 Pulso (Pulse)',
            'fa-stethoscope' => '🩺 Estetoscopio (Stethoscope)',
            'fa-syringe' => '💉 Jeringa (Syringe)',
            'fa-pills' => '💊 Pastillas (Pills)',
            'fa-prescription-bottle' => '💊 Botella Receta (Prescription Bottle)',
            'fa-prescription-bottle-alt' => ' Botella Receta Alt (Prescription Bottle Alt)',
            'fa-medkit' => ' Botiquín (Medkit)',
            'fa-first-aid' => '🩹 Primeros Auxilios (First Aid)',
            'fa-band-aid' => '🩹 Curita (Band Aid)',
            'fa-thermometer' => '️ Termómetro (Thermometer)',
            'fa-thermometer-full' => '️ Termómetro Lleno (Thermometer Full)',
            'fa-thermometer-half' => '🌡️ Termómetro Medio (Thermometer Half)',
            'fa-thermometer-quarter' => '🌡️ Termómetro Cuarto (Thermometer Quarter)',
            'fa-thermometer-empty' => '🌡️ Termómetro Vacío (Thermometer Empty)',
            'fa-x-ray' => '🩻 Rayos X (X Ray)',
            'fa-brain' => '🧠 Cerebro (Brain)',
            'fa-lungs' => '🫁 Pulmones (Lungs)',
            'fa-tooth' => '🦷 Diente (Tooth)',
            'fa-bone' => '🦴 Hueso (Bone)',
            'fa-eye' => '👁️ Ojo (Eye)',
            'fa-eye-dropper' => '💧 Cuentagotas (Eye Dropper)',
            'fa-hand-holding-medical' => '🩺 Médico (Hand Holding Medical)',
            'fa-head-side-cough' => '🤧 Toser (Head Side Cough)',
            'fa-head-side-mask' => '😷 Mascarilla (Head Side Mask)',

            // ═══════════════════════════════════════════════════════════
            // 🎓 EDUCACIÓN Y APRENDIZAJE (20 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-graduation-cap' => ' Gorro Graduación (Graduation Cap)',
            'fa-book' => '📖 Libro (Book)',
            'fa-book-open' => ' Libro Abierto (Book Open)',
            'fa-book-reader' => '📖 Lector (Book Reader)',
            'fa-bookmark' => '🔖 Marcador (Bookmark)',
            'fa-library' => ' Biblioteca (Library)',
            'fa-pen-fancy' => '🖊️ Pluma Elegante (Pen Fancy)',
            'fa-pen-nib' => '️ Punta Pluma (Pen Nib)',
            'fa-pencil-ruler' => '✏️ Lápiz Regla (Pencil Ruler)',
            'fa-ruler' => '📏 Regla (Ruler)',
            'fa-ruler-combined' => '📏 Regla Combinada (Ruler Combined)',
            'fa-ruler-horizontal' => '📏 Regla Horizontal (Ruler Horizontal)',
            'fa-ruler-vertical' => '📏 Regla Vertical (Ruler Vertical)',
            'fa-highlighter' => '🖍️ Marcador (Highlighter)',
            'fa-marker' => '️ Marcador (Marker)',
            'fa-chalkboard' => '📋 Pizarra (Chalkboard)',
            'fa-chalkboard-teacher' => '👨🏫 Profesor (Chalkboard Teacher)',
            'fa-school' => ' Escuela (School)',
            'fa-university' => '🏛️ Universidad (University)',
            'fa-microscope' => '🔬 Microscopio (Microscope)',

            // ═══════════════════════════════════════════════════════════
            // 🏠 HOGAR Y VIDA DIARIA (25 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-home' => '🏠 Casa (Home)',
            'fa-home-alt' => ' Casa Alt (Home Alt)',
            'fa-building' => '🏢 Edificio (Building)',
            'fa-hospital' => '🏥 Hospital (Hospital)',
            'fa-hospital-alt' => '🏥 Hospital Alt (Hospital Alt)',
            'fa-hotel' => '🏨 Hotel (Hotel)',
            'fa-house-damage' => '🏚️ Casa Dañada (House Damage)',
            'fa-warehouse' => '🏭 Almacén (Warehouse)',
            'fa-church' => '⛪ Iglesia (Church)',
            'fa-mosque' => '🕌 Mezquita (Mosque)',
            'fa-synagogue' => '🕍 Sinagoga (Synagogue)',
            'fa-vihara' => '🛕 Vihara (Vihara)',
            'fa-place-of-worship' => '🙏 Lugar Adoración (Place of Worship)',
            'fa-bed' => '🛏️ Cama (Bed)',
            'fa-couch' => '🛋️ Sofá (Couch)',
            'fa-chair' => ' Silla (Chair)',
            'fa-bath' => '🛁 Baño (Bath)',
            'fa-shower' => '🚿 Ducha (Shower)',
            'fa-toilet' => ' Inodoro (Toilet)',
            'fa-sink' => '🚰 Lavabo (Sink)',
            'fa-utensils' => '🍴 Cubiertos (Utensils)',
            'fa-utensil-spoon' => '🥄 Cuchara (Utensil Spoon)',
            'fa-blender' => '🫙 Licuadora (Blender)',
            'fa-mug-hot' => '☕ Taza Caliente (Mug Hot)',
            'fa-coffee' => '☕ Café (Coffee)',

            // ═══════════════════════════════════════════════════════════
            // 🎨 DISEÑO Y CREATIVIDAD (20 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-palette' => '🎨 Paleta (Palette)',
            'fa-paint-brush' => '🖌️ Pincel (Paint Brush)',
            'fa-paint-roller' => '🎨 Rodillo (Paint Roller)',
            'fa-swatchbook' => ' Muestrario (Swatchbook)',
            'fa-bezier-curve' => '〰️ Curva Bezier (Bezier Curve)',
            'fa-vector-square' => '⬜ Vector Cuadrado (Vector Square)',
            'fa-crop' => '✂️ Recortar (Crop)',
            'fa-crop-alt' => '✂️ Recortar Alt (Crop Alt)',
            'fa-object-group' => '🔲 Agrupar (Object Group)',
            'fa-object-ungroup' => '🔲 Desagrupar (Object Ungroup)',
            'fa-layer-group' => '📚 Capas (Layer Group)',
            'fa-copy' => ' Copiar (Copy)',
            'fa-paste' => '📋 Pegar (Paste)',
            'fa-cut' => '️ Cortar (Cut)',
            'fa-clone' => '👥 Clonar (Clone)',
            'fa-fill' => ' Rellenar (Fill)',
            'fa-fill-drip' => '🪣 Rellenar Goteo (Fill Drip)',
            'fa-drafting-compass' => '📐 Compás (Drafting Compass)',
            'fa-drafting-compass' => '📐 Compás (Drafting Compass)',
            'fa-pen-ruler' => '📐 Pluma Regla (Pen Ruler)',

            // ═══════════════════════════════════════════════════════════
            // 🔢 NÚMEROS Y FORMAS (20 iconos)
            // ═══════════════════════════════════════════════════════════
            'fa-circle' => '⭕ Círculo (Circle)',
            'fa-square' => ' Cuadrado (Square)',
            'fa-triangle' => '🔺 Triángulo (Triangle)',
            'fa-hexagon' => '⬡ Hexágono (Hexagon)',
            'fa-octagon' => '⬢ Octágono (Octagon)',
            'fa-pentagon' => ' Pentágono (Pentagon)',
            'fa-diamond' => '💎 Diamante (Diamond)',
            'fa-star' => '⭐ Estrella (Star)',
            'fa-heart' => '❤️ Corazón (Heart)',
            'fa-plus' => '➕ Más (Plus)',
            'fa-minus' => '➖ Menos (Minus)',
            'fa-times' => '✕ X (Times)',
            'fa-check' => '✓ Check (Check)',
            'fa-equals' => '＝ Igual (Equals)',
            'fa-not-equal' => '≠ No Igual (Not Equal)',
            'fa-greater-than' => '＞ Mayor Que (Greater Than)',
            'fa-less-than' => '＜ Menor Que (Less Than)',
            'fa-percentage' => '％ Porcentaje (Percentage)',
            'fa-infinity' => '∞ Infinito (Infinity)',
            'fa-hashtag' => '# Hashtag (Hashtag)',
        ];
    }
}
