<?php

namespace App\Filament\Traits;

trait HasLucideIcons
{
    /**
     * Obtiene todas las opciones de iconos de Lucide disponibles
     *
     * @return array
     */
    public static function getLucideIcons(): array
    {
        return [
            // Negocios y Trabajo
            'Briefcase' => '💼 Maletín (Briefcase)',
            'Building' => '🏢 Edificio (Building)',
            'Building2' => '🏭 Edificio Industrial (Building2)',
            'Factory' => '🏭 Fábrica (Factory)',
            'Warehouse' => '🏭 Almacén (Warehouse)',
            'Store' => '🏪 Tienda (Store)',
            'ShoppingCart' => '🛒 Carrito de Compras (ShoppingCart)',
            'ShoppingBag' => '🛍️ Bolsa de Compras (ShoppingBag)',
            'Package' => '📦 Paquete (Package)',
            'Package2' => '📦 Paquete 2 (Package2)',
            'Box' => '📦 Caja (Box)',
            'Container' => '📦 Contenedor (Container)',
            'Clipboard' => '📋 Portapapeles (Clipboard)',
            'ClipboardList' => '📋 Lista (ClipboardList)',
            'ClipboardCheck' => '📋 Verificado (ClipboardCheck)',
            'FileText' => '📄 Documento (FileText)',
            'File' => '📄 Archivo (File)',
            'Files' => '📄 Archivos (Files)',
            'Folder' => '📁 Carpeta (Folder)',
            'FolderOpen' => '📂 Carpeta Abierta (FolderOpen)',

            // Herramientas y Configuración
            'Settings' => '⚙️ Configuración (Settings)',
            'Tool' => '🔧 Herramienta (Tool)',
            'Wrench' => '🔧 Llave Inglesa (Wrench)',
            'Hammer' => '🔨 Martillo (Hammer)',
            'Screwdriver' => '🪛 Destornillador (Screwdriver)',
            'Tools' => '🛠️ Herramientas (Tools)',
            'Cog' => '⚙️ Engranaje (Cog)',
            'Cogs' => '⚙️ Engranajes (Cogs)',
            'Gear' => '⚙️ Engranaje (Gear)',
            'Sliders' => '🎛️ Controles (Sliders)',
            'Database' => '💾 Base de Datos (Database)',
            'Server' => '🖥️ Servidor (Server)',
            'HardDrive' => '💿 Disco Duro (HardDrive)',
            'Cpu' => '🖥️ Procesador (Cpu)',
            'Microchip' => '💾 Microchip (Microchip)',

            // Usuarios y Personas
            'User' => '👤 Usuario (User)',
            'Users' => '👥 Usuarios (Users)',
            'UserCheck' => '👤 Verificado (UserCheck)',
            'UserX' => '👤 Eliminado (UserX)',
            'UserPlus' => '👤 Agregar Usuario (UserPlus)',
            'UserMinus' => '👤 Eliminar Usuario (UserMinus)',
            'UserCog' => '👤 Configurar Usuario (UserCog)',
            'Contact' => '📇 Contacto (Contact)',
            'ContactRound' => '📇 Contacto Redondo (ContactRound)',
            'IdCard' => '🪪 Tarjeta de Identidad (IdCard)',
            'Badge' => '️ Insignia (Badge)',
            'BadgeCheck' => '🎖️ Verificado (BadgeCheck)',

            // Comunicación
            'MessageSquare' => '💬 Mensaje (MessageSquare)',
            'MessageCircle' => '💬 Círculo de Mensaje (MessageCircle)',
            'Mail' => '✉️ Correo (Mail)',
            'Inbox' => '📥 Bandeja de Entrada (Inbox)',
            'Send' => '✈️ Enviar (Send)',
            'Phone' => '📞 Teléfono (Phone)',
            'PhoneCall' => '📞 Llamada (PhoneCall)',
            'PhoneIncoming' => '📞 Llamada Entrante (PhoneIncoming)',
            'PhoneOutgoing' => '📞 Llamada Saliente (PhoneOutgoing)',
            'Video' => '📹 Video (Video)',
            'VideoOff' => '📹 Video Apagado (VideoOff)',
            'Camera' => '📷 Cámara (Camera)',
            'CameraOff' => '📷 Cámara Apagada (CameraOff)',
            'Image' => '🖼️ Imagen (Image)',
            'Images' => '🖼️ Imágenes (Images)',

            // Tiempo y Calendario
            'Clock' => '🕐 Reloj (Clock)',
            'Clock1' => '🕐 Reloj 1 (Clock1)',
            'Clock2' => '🕑 Reloj 2 (Clock2)',
            'Clock3' => '🕒 Reloj 3 (Clock3)',
            'Clock4' => '🕓 Reloj 4 (Clock4)',
            'Calendar' => '📅 Calendario (Calendar)',
            'CalendarDays' => '📅 Días (CalendarDays)',
            'CalendarCheck' => '📅 Verificado (CalendarCheck)',
            'CalendarX' => '📅 Cancelado (CalendarX)',
            'CalendarPlus' => '📅 Agregar (CalendarPlus)',
            'Timer' => '⏲️ Temporizador (Timer)',
            'Stopwatch' => '⏱️ Cronómetro (Stopwatch)',
            'History' => '🕰️ Historial (History)',
            'Hourglass' => '⏳ Reloj de Arena (Hourglass)',

            // Ubicación y Mapas
            'MapPin' => '📍 Ubicación (MapPin)',
            'Map' => '🗺️ Mapa (Map)',
            'Navigation' => '🧭 Navegación (Navigation)',
            'Navigation2' => '🧭 Navegación 2 (Navigation2)',
            'Compass' => '🧭 Brújula (Compass)',
            'Globe' => '🌍 Globo (Globe)',
            'Globe2' => '🌍 Globo 2 (Globe2)',
            'MapPinned' => '📍 Marcado (MapPinned)',
            'Location' => '📍 Localización (Location)',
            'Pin' => '📍 Pin (Pin)',
            'PinOff' => '📍 Pin Apagado (PinOff)',

            // Alertas y Notificaciones
            'Bell' => '🔔 Campana (Bell)',
            'BellRing' => '🔔 Campana Sonando (BellRing)',
            'BellOff' => '🔔 Campana Apagada (BellOff)',
            'BellPlus' => '🔔 Agregar Notificación (BellPlus)',
            'BellMinus' => '🔔 Quitar Notificación (BellMinus)',
            'AlertCircle' => '⚠️ Alerta Círculo (AlertCircle)',
            'AlertTriangle' => '⚠️ Alerta Triángulo (AlertTriangle)',
            'AlertOctagon' => '⚠️ Alerta Octágono (AlertOctagon)',
            'Info' => 'ℹ️ Información (Info)',
            'XCircle' => '❌ Círculo X (XCircle)',
            'CheckCircle' => '✅ Círculo Check (CheckCircle)',
            'XOctagon' => '❌ Octágono X (XOctagon)',
            'HelpCircle' => '❓ Círculo Ayuda (HelpCircle)',
            'QuestionMark' => '❓ Signo de Pregunta (QuestionMark)',

            // Éxito, Error y Estados
            'Check' => '✓ Check (Check)',
            'CheckSquare' => '✓ Cuadrado Check (CheckSquare)',
            'CheckCircle2' => '✅ Círculo Check 2 (CheckCircle2)',
            'X' => '✕ X (X)',
            'XSquare' => '✕ Cuadrado X (XSquare)',
            'Minus' => '➖ Menos (Minus)',
            'MinusCircle' => '➖ Círculo Menos (MinusCircle)',
            'MinusSquare' => '➖ Cuadrado Menos (MinusSquare)',
            'Plus' => '➕ Más (Plus)',
            'PlusCircle' => '➕ Círculo Más (PlusCircle)',
            'PlusSquare' => '➕ Cuadrado Más (PlusSquare)',
            'ToggleLeft' => '🔘 Toggle Izquierda (ToggleLeft)',
            'ToggleRight' => '🔘 Toggle Derecha (ToggleRight)',

            // Flechas y Dirección
            'ArrowRight' => '➡️ Flecha Derecha (ArrowRight)',
            'ArrowLeft' => '⬅️ Flecha Izquierda (ArrowLeft)',
            'ArrowUp' => '⬆️ Flecha Arriba (ArrowUp)',
            'ArrowDown' => '⬇️ Flecha Abajo (ArrowDown)',
            'ArrowRightCircle' => '➡️ Círculo Flecha Derecha (ArrowRightCircle)',
            'ArrowLeftCircle' => '⬅️ Círculo Flecha Izquierda (ArrowLeftCircle)',
            'ArrowUpCircle' => '⬆️ Círculo Flecha Arriba (ArrowUpCircle)',
            'ArrowDownCircle' => '⬇️ Círculo Flecha Abajo (ArrowDownCircle)',
            'ChevronRight' => '› Chevron Derecha (ChevronRight)',
            'ChevronLeft' => '‹ Chevron Izquierda (ChevronLeft)',
            'ChevronUp' => '› Chevron Arriba (ChevronUp)',
            'ChevronDown' => '› Chevron Abajo (ChevronDown)',
            'ChevronsRight' => '» Doble Chevron Derecha (ChevronsRight)',
            'ChevronsLeft' => '« Doble Chevron Izquierda (ChevronsLeft)',
            'ChevronsUp' => '» Doble Chevron Arriba (ChevronsUp)',
            'ChevronsDown' => '» Doble Chevron Abajo (ChevronsDown)',

            // Acciones
            'Search' => '🔍 Buscar (Search)',
            'Filter' => '🔽 Filtro (Filter)',
            'SortAsc' => '⬆️ Ordenar Ascendente (SortAsc)',
            'SortDesc' => '⬇️ Ordenar Descendente (SortDesc)',
            'Refresh' => '🔄 Actualizar (Refresh)',
            'RotateCcw' => '↶ Rotar Anti-horario (RotateCcw)',
            'RotateCw' => '↷ Rotar Horario (RotateCw)',
            'Download' => '⬇️ Descargar (Download)',
            'Upload' => '⬆️ Subir (Upload)',
            'UploadCloud' => '☁️ Subir a Nube (UploadCloud)',
            'DownloadCloud' => '☁️ Descargar de Nube (DownloadCloud)',
            'Cloud' => '☁️ Nube (Cloud)',
            'CloudOff' => '☁️ Nube Apagada (CloudOff)',
            'LogOut' => '🚪 Cerrar Sesión (LogOut)',
            'LogIn' => '🚪 Iniciar Sesión (LogIn)',
            'Lock' => '🔒 Candado (Lock)',
            'Unlock' => '🔓 Desbloquear (Unlock)',
            'Key' => '🔑 Llave (Key)',
            'KeyRound' => '🔑 Llave Redonda (KeyRound)',

            // Seguridad
            'Shield' => '🛡️ Escudo (Shield)',
            'ShieldCheck' => '🛡️ Escudo Verificado (ShieldCheck)',
            'ShieldAlert' => '🛡️ Escudo Alerta (ShieldAlert)',
            'ShieldOff' => '🛡️ Escudo Apagado (ShieldOff)',
            'Eye' => '👁️ Ojo (Eye)',
            'EyeOff' => '👁️ Ojo Cerrado (EyeOff)',
            'View' => '👁️ Ver (View)',
            'Hide' => '️ Ocultar (Hide)',
            'Scan' => '📷 Escanear (Scan)',
            'ScanFace' => ' Escanear Rostro (ScanFace)',
            'Fingerprint' => '🔐 Huella Digital (Fingerprint)',

            // Finanzas y Comercio
            'CreditCard' => '💳 Tarjeta de Crédito (CreditCard)',
            'Wallet' => '👛 Cartera (Wallet)',
            'WalletCards' => '👛 Tarjetas (WalletCards)',
            'Banknote' => '💵 Billete (Banknote)',
            'Coins' => '🪙 Monedas (Coins)',
            'PiggyBank' => '🐷 Alcancía (PiggyBank)',
            'Receipt' => '🧾 Recibo (Receipt)',
            'ReceiptText' => '🧾 Recibo Texto (ReceiptText)',
            'Ticket' => '🎫 Boleto (Ticket)',
            'TicketCheck' => '🎫 Boleto Verificado (TicketCheck)',
            'Tag' => '🏷️ Etiqueta (Tag)',
            'Tags' => '🏷️ Etiquetas (Tags)',
            'Barcode' => '📊 Código de Barras (Barcode)',
            'QrCode' => '📱 Código QR (QrCode)',

            // Educación y Aprendizaje
            'GraduationCap' => '🎓 Gorro de Graduación (GraduationCap)',
            'Book' => '📖 Libro (Book)',
            'BookOpen' => '📖 Libro Abierto (BookOpen)',
            'BookText' => '📖 Libro Texto (BookText)',
            'BookOpenText' => '📖 Libro Abierto Texto (BookOpenText)',
            'Notebook' => '📓 Cuaderno (Notebook)',
            'NotebookText' => '📓 Cuaderno Texto (NotebookText)',
            'NotebookTabs' => '📓 Cuaderno Pestañas (NotebookTabs)',
            'PenTool' => '🖊️ Herramienta Pluma (PenTool)',
            'Pencil' => '✏️ Lápiz (Pencil)',
            'PencilLine' => '✏️ Línea de Lápiz (PencilLine)',
            'Eraser' => '🧽 Borrador (Eraser)',
            'Highlighter' => '🖍️ Marcador (Highlighter)',

            // Multimedia y Entretenimiento
            'Music' => '🎵 Música (Music)',
            'Music2' => '🎵 Música 2 (Music2)',
            'Music3' => '🎵 Música 3 (Music3)',
            'Music4' => '🎵 Música 4 (Music4)',
            'Play' => '▶️ Reproducir (Play)',
            'Pause' => '⏸️ Pausar (Pause)',
            'Stop' => '⏹️ Detener (Stop)',
            'SkipForward' => '⏭️ Adelantar (SkipForward)',
            'SkipBack' => '⏮️ Retroceder (SkipBack)',
            'Volume' => '🔊 Volumen (Volume)',
            'Volume2' => '🔊 Volumen 2 (Volume2)',
            'VolumeX' => '🔇 Volumen Silenciado (VolumeX)',
            'Mic' => '🎤 Micrófono (Mic)',
            'MicOff' => '🎤 Micrófono Apagado (MicOff)',
            'Radio' => '📻 Radio (Radio)',
            'Podcast' => '🎙️ Podcast (Podcast)',
            'Film' => '🎬 Película (Film)',
            'Tv' => '📺 Televisión (Tv)',
            'Tv2' => '📺 Televisión 2 (Tv2)',
            'Monitor' => '🖥️ Monitor (Monitor)',
            'MonitorPlay' => '🖥️ Monitor Reproduciendo (MonitorPlay)',
            'Smartphone' => '📱 Smartphone (Smartphone)',
            'Tablet' => '📱 Tablet (Tablet)',
            'Laptop' => '💻 Laptop (Laptop)',
            'Computer' => '💻 Computadora (Computer)',
            'Gamepad2' => '🎮 Control de Juego (Gamepad2)',
            'Joystick' => '🕹️ Joystick (Joystick)',

            // Deportes y Actividades
            'Trophy' => '🏆 Trofeo (Trophy)',
            'Medal' => '🏅 Medalla (Medal)',
            'Target' => '🎯 Objetivo (Target)',
            'Flag' => '🚩 Bandera (Flag)',
            'FlagTriangleRight' => '🚩 Bandera Triángulo Derecha (FlagTriangleRight)',
            'FlagTriangleLeft' => '🚩 Bandera Triángulo Izquierda (FlagTriangleLeft)',
            'FlagOff' => '🚩 Bandera Apagada (FlagOff)',
            'Activity' => '📊 Actividad (Activity)',
            'Pulse' => '💓 Pulso (Pulse)',
            'Heart' => '❤️ Corazón (Heart)',
            'HeartHandshake' => '❤️ Corazón Apretón de Manos (HeartHandshake)',
            'HeartOff' => '💔 Corazón Roto (HeartOff)',
            'ThumbsUp' => '👍 Me Gusta (ThumbsUp)',
            'ThumbsDown' => '👎 No Me Gusta (ThumbsDown)',
            'Star' => '⭐ Estrella (Star)',
            'StarOff' => '⭐ Estrella Apagada (StarOff)',
            'Zap' => '⚡ Rayo (Zap)',
            'ZapOff' => '⚡ Rayo Apagado (ZapOff)',
            'Flame' => '🔥 Llama (Flame)',
            'FlameKindling' => '🔥 Llama Encendiendo (FlameKindling)',
            'Lightbulb' => '💡 Bombilla (Lightbulb)',
            'LightbulbOff' => '💡 Bombilla Apagada (LightbulbOff)',

            // Naturaleza y Clima
            'Sun' => '☀️ Sol (Sun)',
            'SunDim' => '☀️ Sol Tenue (SunDim)',
            'Moon' => '🌙 Luna (Moon)',
            'Cloud' => '☁️ Nube (Cloud)',
            'CloudRain' => '🌧️ Lluvia (CloudRain)',
            'CloudSnow' => '❄️ Nieve (CloudSnow)',
            'CloudLightning' => '⛈️ Tormenta (CloudLightning)',
            'CloudDrizzle' => '🌦️ Llovizna (CloudDrizzle)',
            'Wind' => '💨 Viento (Wind)',
            'Umbrella' => '☂️ Paraguas (Umbrella)',
            'Droplet' => '💧 Gota (Droplet)',
            'Droplets' => '💧 Gotas (Droplets)',
            'Thermometer' => '🌡️ Termómetro (Thermometer)',
            'ThermometerSun' => '🌡️ Termómetro Sol (ThermometerSun)',
            'ThermometerSnowflake' => '🌡️ Termómetro Nieve (ThermometerSnowflake)',

            // Comida y Bebida
            'Coffee' => '☕ Café (Coffee)',
            'CupSoda' => '🥤 Vaso de Refresco (CupSoda)',
            'Wine' => '🍷 Vino (Wine)',
            'Beer' => '🍺 Cerveza (Beer)',
            'Utensils' => '🍴 Cubiertos (Utensils)',
            'UtensilsCrossed' => '🍴 Cubiertos Cruzados (UtensilsCrossed)',
            'Pizza' => '🍕 Pizza (Pizza)',
            'Cake' => '🎂 Pastel (Cake)',
            'Cookie' => '🍪 Galleta (Cookie)',
            'Candy' => '🍬 Dulce (Candy)',
            'IceCreamBowl' => '🍨 Helado (IceCreamBowl)',
            'Cherry' => '🍒 Cereza (Cherry)',
            'Apple' => '🍎 Manzana (Apple)',
            'Orange' => '🍊 Naranja (Orange)',
            'Banana' => '🍌 Banana (Banana)',

            // Animales
            'Dog' => '🐶 Perro (Dog)',
            'Cat' => '🐱 Gato (Cat)',
            'Bird' => '🐦 Pájaro (Bird)',
            'Rabbit' => '🐰 Conejo (Rabbit)',
            'Turtle' => '🐢 Tortuga (Turtle)',
            'Fish' => '🐟 Pez (Fish)',
            'FishSymbol' => '🐟 Símbolo Pez (FishSymbol)',
            'Bug' => '🐛 Insecto (Bug)',
            'Butterfly' => '🦋 Mariposa (Butterfly)',
            'Snail' => '🐌 Caracol (Snail)',
            'Flower' => '🌸 Flor (Flower)',
            'Flower2' => '🌸 Flor 2 (Flower2)',
            'Leaf' => '🍃 Hoja (Leaf)',
            'TreePine' => '🌲 Pino (TreePine)',
            'TreeDeciduous' => '🌳 Árbol Caducifolio (TreeDeciduous)',
            'Trees' => '🌳 Árboles (Trees)',

            // Vehículos y Transporte
            'Car' => '🚗 Auto (Car)',
            'CarFront' => '🚗 Auto Frente (CarFront)',
            'CarTaxiFront' => '🚕 Taxi (CarTaxiFront)',
            'Truck' => '🚚 Camión (Truck)',
            'Bus' => '🚌 Bus (Bus)',
            'Bike' => '🚲 Bicicleta (Bike)',
            'Bicycle' => '🚲 Bicicleta (Bicycle)',
            'Motorbike' => '🏍️ Motocicleta (Motorbike)',
            'Ship' => '🚢 Barco (Ship)',
            'Boat' => '⛵ Barco (Boat)',
            'Plane' => '✈️ Avión (Plane)',
            'Rocket' => '🚀 Cohete (Rocket)',
            'TrainFront' => '🚆 Tren (TrainFront)',
            'TrainTrack' => '🛤️ Vía de Tren (TrainTrack)',

            // Construcción e Industria
            'Construction' => '🏗️ Construcción (Construction)',
            'Crane' => '🏗️ Grúa (Crane)',
            'Hammer' => '🔨 Martillo (Hammer)',
            'Pickaxe' => '⛏️ Pico (Pickaxe)',
            'Shovel' => '🪚 Pala (Shovel)',
            'Ruler' => '📏 Regla (Ruler)',
            'RulerDimension' => '📏 Regla Dimensión (RulerDimension)',
            'Scale' => '⚖️ Balanza (Scale)',
            'Scale3d' => '⚖️ Balanza 3D (Scale3d)',
            'Weights' => '🏋️ Pesas (Weights)',
            'Dumbbell' => '🏋️ Pesas Mancuernas (Dumbbell)',
            'Anchor' => '⚓ Ancla (Anchor)',
            'Magnet' => '🧲 Imán (Magnet)',
            'MagnetOff' => '🧲 Imán Apagado (MagnetOff)',
            'Battery' => '🔋 Batería (Battery)',
            'BatteryCharging' => '🔋 Batería Cargando (BatteryCharging)',
            'BatteryFull' => '🔋 Batería Llena (BatteryFull)',
            'BatteryLow' => '🔋 Batería Baja (BatteryLow)',
            'BatteryMedium' => '🔋 Batería Media (BatteryMedium)',
            'Plug' => '🔌 Enchufe (Plug)',
            'PlugZap' => '🔌 Enchufe Rayo (PlugZap)',
            'PlugZap2' => '🔌 Enchufe Rayo 2 (PlugZap2)',
            'Power' => '⚡ Energía (Power)',
            'PowerOff' => '⚡ Energía Apagada (PowerOff)',

            // Símbolos y Formas
            'Circle' => '⭕ Círculo (Circle)',
            'CircleDot' => '⭕ Círculo Punto (CircleDot)',
            'CircleDashed' => '⭕ Círculo Discontinuo (CircleDashed)',
            'CircleSlash' => '⭕ Círculo Barra (CircleSlash)',
            'CircleX' => '⭕ Círculo X (CircleX)',
            'CircleCheck' => '⭕ Círculo Check (CircleCheck)',
            'CircleAlert' => '⭕ Círculo Alerta (CircleAlert)',
            'CircleHelp' => '⭕ Círculo Ayuda (CircleHelp)',
            'CircleMinus' => '⭕ Círculo Menos (CircleMinus)',
            'CirclePlus' => '⭕ Círculo Más (CirclePlus)',
            'Square' => '⬜ Cuadrado (Square)',
            'SquareDot' => '⬜ Cuadrado Punto (SquareDot)',
            'SquareDashed' => '⬜ Cuadrado Discontinuo (SquareDashed)',
            'SquareSlash' => '⬜ Cuadrado Barra (SquareSlash)',
            'SquareX' => '⬜ Cuadrado X (SquareX)',
            'SquareCheck' => '⬜ Cuadrado Check (SquareCheck)',
            'SquareAlert' => '⬜ Cuadrado Alerta (SquareAlert)',
            'SquareHelp' => '⬜ Cuadrado Ayuda (SquareHelp)',
            'SquareMinus' => '⬜ Cuadrado Menos (SquareMinus)',
            'SquarePlus' => '⬜ Cuadrado Más (SquarePlus)',
            'Triangle' => '🔺 Triángulo (Triangle)',
            'TriangleAlert' => '⚠️ Triángulo Alerta (TriangleAlert)',
            'TriangleRight' => '▶️ Triángulo Derecha (TriangleRight)',
            'Diamond' => '💎 Diamante (Diamond)',
            'Hexagon' => '⬡ Hexágono (Hexagon)',
            'Octagon' => '⬢ Octágono (Octagon)',
            'Pentagon' => '⬟ Pentágono (Pentagon)',

            // Redes Sociales (algunas útiles)
            'Github' => '🐙 GitHub (Github)',
            'Gitlab' => '🦊 GitLab (Gitlab)',
            'GitBranch' => '🌿 Rama Git (GitBranch)',
            'GitCommit' => '💾 Commit Git (GitCommit)',
            'GitMerge' => '🔀 Merge Git (GitMerge)',
            'GitPullRequest' => '🔀 Pull Request Git (GitPullRequest)',
            'GitFork' => '🔀 Fork Git (GitFork)',
            'Code' => '💻 Código (Code)',
            'Code2' => '💻 Código 2 (Code2)',
            'Terminal' => '💻 Terminal (Terminal)',
            'TerminalSquare' => '💻 Terminal Cuadrado (TerminalSquare)',
            'Command' => ' Comando (Command)',
            'Option' => '⌥ Opción (Option)',
            'Delete' => '⌫ Eliminar (Delete)',
            'Shift' => '⇧ Shift (Shift)',
            'Control' => '⌃ Control (Control)',

            // Misceláneos útiles
            'Sparkles' => '✨ Brillos (Sparkles)',
            'Sparkle' => '✨ Brillo (Sparkle)',
            'Gem' => '💎 Gema (Gem)',
            'Crown' => '👑 Corona (Crown)',
            'Vibrate' => '📳 Vibrar (Vibrate)',
            'VibrateOff' => '📳 Vibrar Apagado (VibrateOff)',
            'ScanLine' => '📷 Línea de Escaneo (ScanLine)',
            'ScanSearch' => ' Escaneo Búsqueda (ScanSearch)',
            'ScanText' => '📷 Escaneo Texto (ScanText)',
            'ScanFace' => '📷 Escaneo Rostro (ScanFace)',
            'ScanBarcode' => '📷 Escaneo Código de Barras (ScanBarcode)',
            'ScanQrCode' => '📷 Escaneo QR (ScanQrCode)',
            'QrCode' => '📱 Código QR (QrCode)',
            'Barcode' => '📊 Código de Barras (Barcode)',
            'Rss' => '📡 RSS (Rss)',
            'RssFeed' => '📡 Feed RSS (RssFeed)',
            'Share' => '📤 Compartir (Share)',
            'Share2' => '📤 Compartir 2 (Share2)',
            'Link' => '🔗 Enlace (Link)',
            'Link2' => '🔗 Enlace 2 (Link2)',
            'Link2Off' => '🔗 Enlace 2 Roto (Link2Off)',
            'Unlink' => '🔗 Desconectar (Unlink)',
            'ExternalLink' => '🔗 Enlace Externo (ExternalLink)',
            'Anchor' => '⚓ Ancla (Anchor)',
            'Crosshair' => '🎯 Mira (Crosshair)',
            'Target' => '🎯 Objetivo (Target)',
            'Bullseye' => '🎯 Diana (Bullseye)',
        ];
    }
}
